remote_theme: ankitsultana/researcher@gem

title: Sebin Jung
url: "https://sbjung.github.io/"
baseurl: "https://sbjung.github.io/"

markdown: kramdown
ins_logo: "./cmu-wordmark-stacked-k.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://sbjung.github.io/"
 - name: "Resume"
   link: "CV_renewed.pdf"
 - name: "Contact"
   link: "contact"