remote_theme: ankitsultana/researcher@gem

favicon: true
favicon_location: /assets/favicon.png  # or wherever you put it

title: Sebin Jung
url: "https://sbjung.github.io/"
# baseurl: "https://sbjung.github.io/"

markdown: kramdown
# ins_logo: "./cmu-wordmark-horizontal-70k.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
#  - name: "About"
#    link: "https://sbjung.github.io/"
 - name: "Email"
   link: "mailto:sebinj@andrew.cmu.edu"
 - name: "CV"
   link: "CV_renewed.pdf"
#  - name: "Contact"
#    link: "contact"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/sebin-jung-a42884248/"
 - name: "Scholar"
   link: "https://scholar.google.com/citations?hl=en&user=bqhB0foAAAAJ"
 - name: "GitHub" 
   link: "https://github.com/SBJung"